[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Nazar Palamarenko", email = "nazarpalamarenkoo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
