"""add_knowledge_domains_and_usage_event_logs

Revision ID: 00327087014f
Revises: 5f93cdc08ee3
Create Date: 2026-08-20 14:25:51.643249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00327087014f'
down_revision: Union[str, Sequence[str], None] = '5f93cdc08ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('parent_domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['knowledge_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_domains_parent_domain_id'), 'knowledge_domains', ['parent_domain_id'], unique=False)
    op.create_index(op.f('ix_knowledge_domains_slug'), 'knowledge_domains', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tag_name'), 'tags', ['tag_name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=1000), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('BOOK', 'ARCHITECTURE_DOC', 'PAPER', 'MANUAL', 'BLOG_POST', name='document_type'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('embedding_model', sa.String(length=150), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['knowledge_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'content_hash', 'version', name='uq_document_source_hash_version')
    )
    op.create_index(op.f('ix_documents_domain_id'), 'documents', ['domain_id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_id_chunk_index'),
    sa.UniqueConstraint('qdrant_point_id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_index('ix_document_tags_tag_id', 'document_tags', ['tag_id'], unique=False)
    op.create_table('skill_usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('config_bundle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_bundle_id'], ['config_bundles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_usage_events_config_bundle_id'), 'skill_usage_events', ['config_bundle_id'], unique=False)
    op.create_index(op.f('ix_skill_usage_events_skill_id'), 'skill_usage_events', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_usage_events_user_id'), 'skill_usage_events', ['user_id'], unique=False)
    op.create_table('tool_usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('config_bundle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_bundle_id'], ['config_bundles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_usage_events_config_bundle_id'), 'tool_usage_events', ['config_bundle_id'], unique=False)
    op.create_index(op.f('ix_tool_usage_events_tool_id'), 'tool_usage_events', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_usage_events_user_id'), 'tool_usage_events', ['user_id'], unique=False)
    op.drop_constraint(op.f('config_bundles_user_id_fkey'), 'config_bundles', type_='foreignkey')
    op.create_foreign_key(None, 'config_bundles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('skills', sa.Column('domain_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skills_domain_id'), 'skills', ['domain_id'], unique=False)
    op.create_unique_constraint('uq_skill_name_domain', 'skills', ['skill_name', 'domain_id'])
    op.create_foreign_key(None, 'skills', 'knowledge_domains', ['domain_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('token_usage_events_user_id_fkey'), 'token_usage_events', type_='foreignkey')
    op.drop_constraint(op.f('token_usage_events_agent_id_fkey'), 'token_usage_events', type_='foreignkey')
    op.create_foreign_key(None, 'token_usage_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'token_usage_events', 'agent_profiles', ['agent_id'], ['id'], ondelete='SET NULL')
    op.add_column('tools', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tools_domain_id'), 'tools', ['domain_id'], unique=False)
    op.create_foreign_key(None, 'tools', 'knowledge_domains', ['domain_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_index(op.f('ix_tools_domain_id'), table_name='tools')
    op.drop_column('tools', 'domain_id')
    op.drop_constraint(None, 'token_usage_events', type_='foreignkey')
    op.drop_constraint(None, 'token_usage_events', type_='foreignkey')
    op.create_foreign_key(op.f('token_usage_events_agent_id_fkey'), 'token_usage_events', 'agent_profiles', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('token_usage_events_user_id_fkey'), 'token_usage_events', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint('uq_skill_name_domain', 'skills', type_='unique')
    op.drop_index(op.f('ix_skills_domain_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.drop_column('skills', 'domain_id')
    op.drop_constraint(None, 'config_bundles', type_='foreignkey')
    op.create_foreign_key(op.f('config_bundles_user_id_fkey'), 'config_bundles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tool_usage_events_user_id'), table_name='tool_usage_events')
    op.drop_index(op.f('ix_tool_usage_events_tool_id'), table_name='tool_usage_events')
    op.drop_index(op.f('ix_tool_usage_events_config_bundle_id'), table_name='tool_usage_events')
    op.drop_table('tool_usage_events')
    op.drop_index(op.f('ix_skill_usage_events_user_id'), table_name='skill_usage_events')
    op.drop_index(op.f('ix_skill_usage_events_skill_id'), table_name='skill_usage_events')
    op.drop_index(op.f('ix_skill_usage_events_config_bundle_id'), table_name='skill_usage_events')
    op.drop_table('skill_usage_events')
    op.drop_index('ix_document_tags_tag_id', table_name='document_tags')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_domain_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_tags_tag_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_knowledge_domains_slug'), table_name='knowledge_domains')
    op.drop_index(op.f('ix_knowledge_domains_parent_domain_id'), table_name='knowledge_domains')
    op.drop_table('knowledge_domains')
    # ### end Alembic commands ###
