"""add skill_domains table

Revision ID: 22b022e6e42b
Revises: 065c893213da
Create Date: 2026-08-31 16:38:23.854033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b022e6e42b'
down_revision: Union[str, Sequence[str], None] = '065c893213da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_codes_device_code_key'), 'device_codes', type_='unique')
    op.create_unique_constraint(op.f('uq_device_codes_device_code'), 'device_codes', ['device_code'])
    op.drop_constraint(op.f('document_chunks_qdrant_point_id_key'), 'document_chunks', type_='unique')
    op.create_unique_constraint(op.f('uq_document_chunks_qdrant_point_id'), 'document_chunks', ['qdrant_point_id'])
    op.drop_constraint(op.f('tools_tool_name_key'), 'tools', type_='unique')
    op.create_unique_constraint(op.f('uq_tools_tool_name'), 'tools', ['tool_name'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_tools_tool_name'), 'tools', type_='unique')
    op.create_unique_constraint(op.f('tools_tool_name_key'), 'tools', ['tool_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_document_chunks_qdrant_point_id'), 'document_chunks', type_='unique')
    op.create_unique_constraint(op.f('document_chunks_qdrant_point_id_key'), 'document_chunks', ['qdrant_point_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_device_codes_device_code'), 'device_codes', type_='unique')
    op.create_unique_constraint(op.f('device_codes_device_code_key'), 'device_codes', ['device_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
