"""Initial migration

Revision ID: 5f93cdc08ee3
Revises: 
Create Date: 2026-08-17 18:23:02.833378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f93cdc08ee3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_agent_name'), 'agent_profiles', ['agent_name'], unique=True)
    op.create_index(op.f('ix_agent_profiles_id'), 'agent_profiles', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('skill_selected_freq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('tool_selected_freq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_name')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_profile_skills',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_index('ix_agent_profile_skills_skill_id', 'agent_profile_skills', ['skill_id'], unique=False)
    op.create_table('agent_profile_tools',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_index('ix_agent_profile_tools_tool_id', 'agent_profile_tools', ['tool_id'], unique=False)
    op.create_table('config_bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_config_bundle_user_name')
    )
    op.create_index(op.f('ix_config_bundles_agent_id'), 'config_bundles', ['agent_id'], unique=False)
    op.create_index(op.f('ix_config_bundles_id'), 'config_bundles', ['id'], unique=False)
    op.create_index(op.f('ix_config_bundles_user_id'), 'config_bundles', ['user_id'], unique=False)
    op.create_table('device_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='device_status'), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_index('ix_device_codes_status_expires_at', 'device_codes', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_device_codes_user_id'), 'device_codes', ['user_id'], unique=False)
    op.create_table('token_usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_events_user_id'), 'token_usage_events', ['user_id'], unique=False)
    op.create_table('config_bundle_skills',
    sa.Column('config_bundle_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_bundle_id'], ['config_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_bundle_id', 'skill_id')
    )
    op.create_index('ix_config_bundle_skills_skill_id', 'config_bundle_skills', ['skill_id'], unique=False)
    op.create_table('config_bundle_tools',
    sa.Column('config_bundle_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_bundle_id'], ['config_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_bundle_id', 'tool_id')
    )
    op.create_index('ix_config_bundle_tools_tool_id', 'config_bundle_tools', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_config_bundle_tools_tool_id', table_name='config_bundle_tools')
    op.drop_table('config_bundle_tools')
    op.drop_index('ix_config_bundle_skills_skill_id', table_name='config_bundle_skills')
    op.drop_table('config_bundle_skills')
    op.drop_index(op.f('ix_token_usage_events_user_id'), table_name='token_usage_events')
    op.drop_table('token_usage_events')
    op.drop_index(op.f('ix_device_codes_user_id'), table_name='device_codes')
    op.drop_index('ix_device_codes_status_expires_at', table_name='device_codes')
    op.drop_table('device_codes')
    op.drop_index(op.f('ix_config_bundles_user_id'), table_name='config_bundles')
    op.drop_index(op.f('ix_config_bundles_id'), table_name='config_bundles')
    op.drop_index(op.f('ix_config_bundles_agent_id'), table_name='config_bundles')
    op.drop_table('config_bundles')
    op.drop_index('ix_agent_profile_tools_tool_id', table_name='agent_profile_tools')
    op.drop_table('agent_profile_tools')
    op.drop_index('ix_agent_profile_skills_skill_id', table_name='agent_profile_skills')
    op.drop_table('agent_profile_skills')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_agent_profiles_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_agent_name'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
