"""add knowledge_packs and link documents/config_bundles

Revision ID: a5f1c1e834b3
Revises: e699f57f2fa3
Create Date: 2026-09-08 11:01:44.326287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f1c1e834b3'
down_revision: Union[str, Sequence[str], None] = 'e699f57f2fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE documents RESTART IDENTITY CASCADE")
    op.create_table('knowledge_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['knowledge_domains.id'], name=op.f('fk_knowledge_packs_domain_id_knowledge_domains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_packs')),
    sa.UniqueConstraint('domain_id', 'name', name='uq_knowledge_pack_domain_name')
    )
    op.create_index(op.f('ix_knowledge_packs_domain_id'), 'knowledge_packs', ['domain_id'], unique=False)
    op.create_index(op.f('ix_knowledge_packs_name'), 'knowledge_packs', ['name'], unique=False)
    op.create_table('tool_domains',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['knowledge_domains.id'], name=op.f('fk_tool_domains_domain_id_knowledge_domains'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_domains_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'domain_id', name=op.f('pk_tool_domains'))
    )
    op.create_index('ix_tool_domains_domain_id', 'tool_domains', ['domain_id'], unique=False)
    op.create_table('config_bundle_knowledge_packs',
    sa.Column('config_bundle_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_pack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_bundle_id'], ['config_bundles.id'], name=op.f('fk_config_bundle_knowledge_packs_config_bundle_id_config_bundles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_pack_id'], ['knowledge_packs.id'], name=op.f('fk_config_bundle_knowledge_packs_knowledge_pack_id_knowledge_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_bundle_id', 'knowledge_pack_id', name=op.f('pk_config_bundle_knowledge_packs'))
    )
    op.create_index('ix_config_bundle_knowledge_packs_pack_id', 'config_bundle_knowledge_packs', ['knowledge_pack_id'], unique=False)
    op.drop_constraint(op.f('fk_config_bundles_user_id_users'), 'config_bundles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_config_bundles_user_id_users'), 'config_bundles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('knowledge_pack_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_documents_domain_id'), table_name='documents')
    op.create_index(op.f('ix_documents_knowledge_pack_id'), 'documents', ['knowledge_pack_id'], unique=False)
    op.create_unique_constraint(op.f('uq_documents_content_hash'), 'documents', ['content_hash'])
    op.drop_constraint(op.f('fk_documents_domain_id_knowledge_domains'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_knowledge_pack_id_knowledge_packs'), 'documents', 'knowledge_packs', ['knowledge_pack_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'domain_id')
    op.drop_constraint(op.f('fk_knowledge_domains_parent_domain_id_knowledge_domains'), 'knowledge_domains', type_='foreignkey')
    op.create_foreign_key(op.f('fk_knowledge_domains_parent_domain_id_knowledge_domains'), 'knowledge_domains', 'knowledge_domains', ['parent_domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_token_usage_events_user_id_users'), 'token_usage_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_token_usage_events_agent_id_agent_profiles'), 'token_usage_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_token_usage_events_user_id_users'), 'token_usage_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_token_usage_events_agent_id_agent_profiles'), 'token_usage_events', 'agent_profiles', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tools_domain_id'), table_name='tools')
    op.drop_constraint(op.f('fk_tools_domain_id_knowledge_domains'), 'tools', type_='foreignkey')
    op.drop_column('tools', 'domain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tools_domain_id_knowledge_domains'), 'tools', 'knowledge_domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tools_domain_id'), 'tools', ['domain_id'], unique=False)
    op.drop_constraint(op.f('fk_token_usage_events_agent_id_agent_profiles'), 'token_usage_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_token_usage_events_user_id_users'), 'token_usage_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_token_usage_events_agent_id_agent_profiles'), 'token_usage_events', 'agent_profiles', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_token_usage_events_user_id_users'), 'token_usage_events', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_knowledge_domains_parent_domain_id_knowledge_domains'), 'knowledge_domains', type_='foreignkey')
    op.create_foreign_key(op.f('fk_knowledge_domains_parent_domain_id_knowledge_domains'), 'knowledge_domains', 'knowledge_domains', ['parent_domain_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_documents_knowledge_pack_id_knowledge_packs'), 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_domain_id_knowledge_domains'), 'documents', 'knowledge_domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_documents_content_hash'), 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_knowledge_pack_id'), table_name='documents')
    op.create_index(op.f('ix_documents_domain_id'), 'documents', ['domain_id'], unique=False)
    op.drop_column('documents', 'knowledge_pack_id')
    op.drop_constraint(op.f('fk_config_bundles_user_id_users'), 'config_bundles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_config_bundles_user_id_users'), 'config_bundles', 'users', ['user_id'], ['id'])
    op.drop_index('ix_config_bundle_knowledge_packs_pack_id', table_name='config_bundle_knowledge_packs')
    op.drop_table('config_bundle_knowledge_packs')
    op.drop_index('ix_tool_domains_domain_id', table_name='tool_domains')
    op.drop_table('tool_domains')
    op.drop_index(op.f('ix_knowledge_packs_name'), table_name='knowledge_packs')
    op.drop_index(op.f('ix_knowledge_packs_domain_id'), table_name='knowledge_packs')
    op.drop_table('knowledge_packs')
    # ### end Alembic commands ###
