"""add skill_domains table

Revision ID: e699f57f2fa3
Revises: 22b022e6e42b
Create Date: 2026-08-31 16:55:06.048479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e699f57f2fa3'
down_revision: Union[str, Sequence[str], None] = '22b022e6e42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_domains',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['knowledge_domains.id'], name=op.f('fk_skill_domains_domain_id_knowledge_domains'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_domains_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'domain_id', name=op.f('pk_skill_domains'))
    )
    op.create_index('ix_skill_domains_domain_id', 'skill_domains', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_domains_domain_id', table_name='skill_domains')
    op.drop_table('skill_domains')
    # ### end Alembic commands ###
