"""add discovered_documents table

Revision ID: 3a20752f7c8d
Revises: d39b7f18ddac
Create Date: 2026-09-24 15:20:36.951333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a20752f7c8d'
down_revision: Union[str, Sequence[str], None] = 'd39b7f18ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'REJECT', name='discovered_document_decision'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('educational_score', sa.Float(), nullable=True),
    sa.Column('implementation_score', sa.Float(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('document_category', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_documents'))
    )
    op.create_index(op.f('ix_discovered_documents_url_hash'), 'discovered_documents', ['url_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_documents_url_hash'), table_name='discovered_documents')
    op.drop_table('discovered_documents')
    # ### end Alembic commands ###
