"""add slug to knowledge_packs

Revision ID: d39b7f18ddac
Revises: a5f1c1e834b3
Create Date: 2026-09-08 11:07:17.045310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39b7f18ddac'
down_revision: Union[str, Sequence[str], None] = 'a5f1c1e834b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_packs', sa.Column('slug', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_knowledge_packs_slug'), 'knowledge_packs', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_packs_slug'), table_name='knowledge_packs')
    op.drop_column('knowledge_packs', 'slug')
    # ### end Alembic commands ###
